### ISSUE TITLE
Route L33 has missing stops

### ISSUE THREAD

**Issue by DomeQdev** [MKuranowski/WarsawGTFS#45]
A strange situation, the locations of the stops and the route are correctly specified in the Pliki Rozkładowe, but GTFS is not generated correctly.

![image](https://github.com/MKuranowski/WarsawGTFS/assets/45435431/cf44908a-1fe8-4301-9e29-a86647c2d238)

**Comment by MKuranowski** [comment]
Looks fine to me (apart from the shape, but that's an OSM issue and it takes time for [the fix](https://www.openstreetmap.org/changeset/141985689) to propagate).

![image](https://github.com/MKuranowski/WarsawGTFS/assets/16469272/2861b449-9fca-4676-84c0-9cbcec060769)

The GTFS published on mkuran.pl will only be updated tommorow (2023-10-02); data for today 2023-10-01 has screwed up trains. I'll investigate whether this is a CM issue in the coming week.

**Comment by DomeQdev** [comment]
Also, today in many brigades schedule, there was a very long break between trips 
![image](https://github.com/MKuranowski/WarsawGTFS/assets/45435431/51d1c755-9213-4b6f-b6d7-9ad242beea17)
