### ISSUE TITLE
Inconsistency in GTFS Data for Warszawa Główna

### ISSUE THREAD

**Issue by DomeQdev** [MKuranowski/WarsawGTFS#47]
I've encountered a specific issue in the GTFS data for Warszawa Główna (`stop_id`: 5909pUnknown). The `parent_station` field references `stop_id` 5909, but this `parent_station` is not present in the dataset. 

This absence is causing errors and inconsistencies in data processing. Can you please confirm whether this is an oversight or if it's intended?

**Comment by MKuranowski** [comment]
Invalid GTFS data is never intended; especially something as grave as foreign key violations. I've fixed the script, thanks for noticing
