### ISSUE TITLE
Download in passive FTP mode

### ISSUE THREAD

**Issue by danieljuschus** [MKuranowski/WarsawGTFS#9]
To make `warsawgtfs.py` work, I had to change line 323 in `downloader.py` to `ftp.set_pasv(True)`.  I'm not sure what exactly this means, but I was getting an error message before and found the fix on Stackoverflow: https://stackoverflow.com/questions/61246610/ftp-error-500-illegal-port-command-while-trying-to-connect-from-a-dockerized-p

**Comment by MKuranowski** [comment]
Some time around Christmas the passive mode (when the server hosts both the commands and data connections) of the FTP server broke and I had to disable it, forcing active FTP mode (when the server only hosts the command connection, the data connection is hosted by the client) (b46629d0fcf0f24bc17f71127b50f72119c66db7).

However, in active mode, and when the client is behind a NAT, usually without proper configuration the server won't be able to connect to the client's data port; see <https://en.wikipedia.org/wiki/File_Transfer_Protocol#Communication_and_data_transfer>.

It seems like ZTM's fixed the FTP configuration and passive mode works again, so we can bring back FTP passive mode.
